name: Build Exe Archive

#on:
#  release:
#    types: [published]

on: workflow_dispatch

jobs:
  build:
    name: Build executable
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install the module
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Build the application
      run: |
        python application/setup.py build
    - name: Store the built application
      uses: actions/upload-artifact@v4
      with:
        name: ducktools-exe
        path: build/
